### ISSUE TITLE
Unregister Player Issue

### ISSUE THREAD

**Issue by WizardJesse1** [apollo-rsps/apollo#103]
When you do ::clientdrop to drop the players connection you get an error like this

java.lang.NullPointerException
	at org.apollo.game.service.GameService.finalizePlayerRegistration(GameService.java:127)
	at org.apollo.game.service.GameService.finalizeRegistrations(GameService.java:224)
	at org.apollo.game.service.GameService.pulse(GameService.java:154)
	at org.apollo.game.GamePulseHandler.run(GamePulseHandler.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

java.lang.NullPointerException
	at org.apollo.game.model.entity.Player.send(Player.java:731)
	at org.apollo.game.sync.task.PrePlayerSynchronizationTask.run(PrePlayerSynchronizationTask.java:80)
	at org.apollo.game.sync.task.PhasedSynchronizationTask.run(PhasedSynchronizationTask.java:40)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

and continues to spam

**Comment by Major-** [comment]
Is this still an issue?

**Comment by WizardJesse1** [comment]
@Major- i have not seen it happen anymore
