### ISSUE TITLE
java.io.FileNotFoundException: No index file(s) present.

### ISSUE THREAD

**Issue by CapslockRSPS** [apollo-rsps/apollo#105]
java.io.FileNotFoundException: No index file(s) present.
	at org.apollo.cache.IndexedFileSystem.detectLayout(IndexedFileSystem.java:279)
	at org.apollo.cache.IndexedFileSystem.<init>(IndexedFileSystem.java:67)
	at org.apollo.Server.init(Server.java:140)
	at org.apollo.Server.main(Server.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

Missing the fs folder inside of data is causing it.

**Comment by lare96** [comment]
You have to add the folder and index files yourself, iirc its

.data/fs/<revision>/

**Comment by CapslockRSPS** [comment]
Where can I get those files.

**Comment by lare96** [comment]
from your client lol they're in the cache
