### ISSUE TITLE
Login Issue When player is already online?

### ISSUE THREAD

**Issue by WizardJesse1** [apollo-rsps/apollo#111]
When you try to login and you get the message ("this player is already online") is still registers a null player i think into the game that does nothing.

java.lang.NullPointerException
	at org.apollo.game.model.entity.Player.send(Player.java:731)
	at
org.apollo.game.sync.task.PlayerSynchronizationTask.run(PlayerSynchronizationTask.java:115)
	at org.apollo.game.sync.task.PhasedSynchronizationTask.run(PhasedSynchronizationTask.java:40)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

How to reproduce this issue

http://recordit.co/rw146iTwyF

**Comment by WizardJesse1** [comment]
https://github.com/apollo-rsps/apollo/pull/119 Fixed
