### ISSUE TITLE
Stuck running Apollo via Eclipse

### ISSUE THREAD

**Issue by adraitz** [apollo-rsps/apollo#300]
I downloded eclipse and installed the ivy de and maven and all that, i right-click maven build it builds flawlessly, but if i try running it via java app. it gives me this error. 

`Mar 31, 2016 1:56:16 PM org.apollo.Server <init>
INFO: Starting Apollo...
Mar 31, 2016 1:56:17 PM org.apollo.Server init
INFO: Initialized Release 377.
Mar 31, 2016 1:56:17 PM org.apollo.Server main
SEVERE: Error whilst starting server.
java.io.FileNotFoundException: data\messages.xml (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at org.apollo.game.service.GameService.init(GameService.java:254)
	at org.apollo.game.service.GameService.<init>(GameService.java:116)
	at org.apollo.ServiceManager.<init>(ServiceManager.java:45)
	at org.apollo.Server.init(Server.java:138)
	at org.apollo.Server.main(Server.java:53)`

i've tried everything, the file is there that is says its missing, i dont understand it. i've been stuck on this for two days, and yes i got this source via this github resp.

**Comment by garyttierney** [comment]
The issue here is that the current working directory of the Server run configuration you've launched is not the root of the project. See http://stackoverflow.com/questions/329129/set-the-execution-directory-in-eclipse
