### ISSUE TITLE
Ruby sometimes classes give NoSuchMethodError

### ISSUE THREAD

**Issue by hlycklama** [apollo-rsps/apollo#308]
Hey,

Great project! I've been playing around with this. I've found an error in the ruby plugin classes that are trying to use properties/methods on the SkillSet class.

For example, when trying to hit a dummy once, everything works as expected. However, after a few times, hitting the dummy again will result in the SkillSet.skill method not being defined / accessable by JRuby and JRuby therefore throws a NoSuchMethodError on the game pulse.

Found also occuring when:
 - using the level command
 - trying to use the magic spellbook

Anyone else have this, or is my there something wrong with my config..

Edit: Here is the stack trace

```
SEVERE: Uncaught exception thrown while handling message: org.apollo.game.message.impl.CommandMessage@290e5589
org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `experience_for_level' for Java::OrgApolloGameModelEntity::SkillSet:Class
	at org.jruby.RubyBasicObject.method_missing(org/jruby/RubyBasicObject.java:1592)
	at RUBY.block in (root)(/Users/hidde/IdeaProjects/apollo/./data/plugins/cmd/skill/skill.rb:23)
	at org.jruby.RubyProc.call(org/jruby/RubyProc.java:318)
	at RUBY.execute(/Users/hidde/IdeaProjects/apollo/./data/plugins/bootstrap.rb:55)
```

Thanks

**Comment by hlycklama** [comment]
Still not working after #309 . Could it be the JRuby version?

**Comment by Major-** [comment]
This is strange... does this error occur in a fresh clone (i.e. in a copy of apollo that you haven't made any changes to)?

**Comment by hlycklama** [comment]
I'll retry that, I have only changed the updateRequired method to always return true, because my client wouldnt let me log in. I'll get back to you in a few hours.

**Comment by hlycklama** [comment]
Clean clone gives a 'GC overhead limit exceeded' at the CollisionUpdate (due to my 377 cache). Increasing the memory limit to 2048M makes it work.

However, the error persists. Could it be a cache issue?

**Comment by garyttierney** [comment]
@hlycklama your client wouldn't let you log in?  Also, when do you see the GC overhead limit exceeded message.  At boot up?

**Comment by hlycklama** [comment]
Yes, the client would get an 'Update available' message from the server, after comparing versions of the cache, even though the server is using the same one as the client.  I'm using some 'clean' 377 client and cache from the web

What client are you using? Is there some reference version I can use?

Also, not sure if you need this, but the GC stacktrace:

`Jan 02, 2017 9:44:33 PM org.apollo.Server <init>
INFO: Starting Apollo...
Jan 02, 2017 9:44:33 PM org.apollo.Server init
INFO: Initialized Release 377.
Jan 02, 2017 9:44:34 PM org.apollo.ServiceManager startAll
INFO: Starting services...
Jan 02, 2017 9:45:25 PM org.apollo.Server main
SEVERE: Error whilst starting server.
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.HashMap.newNode(HashMap.java:1742)
	at java.util.HashMap.putVal(HashMap.java:630)
	at java.util.HashMap.put(HashMap.java:611)
	at java.util.HashSet.add(HashSet.java:219)
	at com.google.common.collect.AbstractMapBasedMultimap.put(AbstractMapBasedMultimap.java:196)
	at com.google.common.collect.AbstractSetMultimap.put(AbstractSetMultimap.java:128)
	at org.apollo.game.model.area.collision.CollisionUpdate$Builder.lambda$tile$0(CollisionUpdate.java:130)
	at org.apollo.game.model.area.collision.CollisionUpdate$Builder$$Lambda$25/905544614.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.apollo.game.model.area.collision.CollisionUpdate$Builder.tile(CollisionUpdate.java:130)
	at org.apollo.game.model.area.collision.CollisionManager.build(CollisionManager.java:77)
	at org.apollo.game.model.World.init(World.java:241)
	at org.apollo.Server.init(Server.java:158)
	at org.apollo.Server.main(Server.java:53)`

**Comment by Major-** [comment]
Looks like as of jruby 9000 static methods can't be accessed using the Javabean aliasing magic (no `object.x` -> `object.getX`).
