### ISSUE TITLE
Server loadup issue for Win 64

### ISSUE THREAD

**Issue by Faris-Mckay** [apollo-rsps/apollo#379]
Could be just me, but worth a mention if anyone else encounters this.
Did a fresh pull on my Windows machine, built and executed. 
`java.lang.OutOfMemoryError: Java heap space
	at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
	at java.lang.StringBuilder.<init>(StringBuilder.java:89)
	at org.apollo.game.model.Position.<init>(Position.java:49)
	at org.apollo.game.model.area.collision.CollisionManager.build(CollisionManager.java:79)
	at org.apollo.game.model.World.init(World.java:241)
	at org.apollo.Server.init(Server.java:158)
	at org.apollo.Server.main(Server.java:53)`

Tried on my Mac OS X, same steps cloned repo, built and ran. worked fine...
I've tried to allocate more memory to the App, still runs out of space.

**Comment by garyttierney** [comment]
Hmm, are you starting the server via Gradle?  I'm not sure why the JVM arguments we set wouldn't be applied here.

**Comment by garyttierney** [comment]
Related to #328

**Comment by Faris-Mckay** [comment]
@garyttierney yeah, running with the Gradle script from bash I'm getting
`Could not reserve enough space for 17920000KB` object heap`
Although I definitely have the space to run this, it does seem odd that my VM can't reserve this space.

Going to try downloading and pointing to a new JDK and seeing if this has any affect, as I think although that is a large amount of memory for a start up; the issue could be with me somewhere.

**Comment by garyttierney** [comment]
Have you changed the Gradle build script at all? 17920000KB is ~18 GB and definitely not what we set as the default heap size.

**Comment by Faris-Mckay** [comment]
I've not changed the build script that could be a typing error, I had to type the message manually as my terminal wouldn't let me copy for some reason.

Interesting development, clean install of JDK (9.0.4), fresh pull of the master branch, getting this new run error during Loading Services. (I now seem able to allocate the memory which is good)

`INFO: Starting services...
org.jruby.embed.EvalFailedException: java.lang.IndexOutOfBoundsException: Id out of bounds. (3673) must be less than size (3509)
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:137)
	at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1307)
	at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1338)
	at org.apollo.game.plugin.RubyPluginEnvironment.parse(RubyPluginEnvironment.java:37)
	at org.apollo.game.plugin.PluginManager.start(PluginManager.java:187)
	at org.apollo.game.plugin.PluginManager.start(PluginManager.java:153)
	at org.apollo.game.model.World.init(World.java:247)
	at org.apollo.Server.init(Server.java:158)
	at org.apollo.Server.main(Server.java:53)
Caused by: java.lang.IndexOutOfBoundsException: Id out of bounds. (3673) must be less than size (3509)
	at com.google.common.base.Preconditions.checkElementIndex(com/google/common/base/Preconditions.java:310)
	at org.apollo.cache.def.NpcDefinition.lookup(org/apollo/cache/def/NpcDefinition.java:59)
	at org.apollo.game.model.entity.Npc.<init>(org/apollo/game/model/entity/Npc.java:33)
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(jdk/internal/reflect/DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(java/lang/reflect/Constructor.java:488)
	at RUBY.get_npc(C:\Users\FarisMcKay\Documents\GitHub\apollo\.\data\plugins\entity\spawning\npc-spawn.rb:57)
	at RUBY.spawn_npc(C:\Users\FarisMcKay\Documents\GitHub\apollo\.\data\plugins\entity\spawning\npc-spawn.rb:36)
	at RUBY.<top>(C:\Users\FarisMcKay\Documents\GitHub\apollo\.\data\plugins\location\edgeville\npcs.rb:21)
	at org.apollo.game.plugin.RubyPluginEnvironment.parse(org/apollo/game/plugin/RubyPluginEnvironment.java:37)
	at org.apollo.game.plugin.PluginManager.start(org/apollo/game/plugin/PluginManager.java:187)
	at org.apollo.game.plugin.PluginManager.start(org/apollo/game/plugin/PluginManager.java:153)
	at org.apollo.game.model.World.init(org/apollo/game/model/World.java:247)
	at org.apollo.Server.init(org/apollo/Server.java:158)
	at org.apollo.Server.main(org/apollo/Server.java:53)
Mar 09, 2018 9:04:29 PM org.apollo.Server main
SEVERE: Error whilst starting server.
java.lang.RuntimeException: Error parsing scriptlet C:\Users\FarisMcKay\Documents\GitHub\apollo\.\data\plugins\location\edgeville\npcs.rb.
	at org.apollo.game.plugin.RubyPluginEnvironment.parse(RubyPluginEnvironment.java:40)
	at org.apollo.game.plugin.PluginManager.start(PluginManager.java:187)
	at org.apollo.game.plugin.PluginManager.start(PluginManager.java:153)
	at org.apollo.game.model.World.init(World.java:247)
	at org.apollo.Server.init(Server.java:158)
	at org.apollo.Server.main(Server.java:53)
Caused by: org.jruby.embed.EvalFailedException: java.lang.IndexOutOfBoundsException: Id out of bounds. (3673) must be less than size (3509)
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:137)
	at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1307)
	at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1338)
	at org.apollo.game.plugin.RubyPluginEnvironment.parse(RubyPluginEnvironment.java:37)
	... 5 more
Caused by: java.lang.IndexOutOfBoundsException: Id out of bounds. (3673) must be less than size (3509)
	at com.google.common.base.Preconditions.checkElementIndex(com/google/common/base/Preconditions.java:310)
	at org.apollo.cache.def.NpcDefinition.lookup(org/apollo/cache/def/NpcDefinition.java:59)
	at org.apollo.game.model.entity.Npc.<init>(org/apollo/game/model/entity/Npc.java:33)
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(jdk/internal/reflect/DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(java/lang/reflect/Constructor.java:488)
	at RUBY.get_npc(C:\Users\FarisMcKay\Documents\GitHub\apollo\.\data\plugins\entity\spawning\npc-spawn.rb:57)
	at RUBY.spawn_npc(C:\Users\FarisMcKay\Documents\GitHub\apollo\.\data\plugins\entity\spawning\npc-spawn.rb:36)
	at RUBY.<top>(C:\Users\FarisMcKay\Documents\GitHub\apollo\.\data\plugins\location\edgeville\npcs.rb:21)
	at org.apollo.game.plugin.RubyPluginEnvironment.parse(org/apollo/game/plugin/RubyPluginEnvironment.java:37)
	at org.apollo.game.plugin.PluginManager.start(org/apollo/game/plugin/PluginManager.java:187)
	at org.apollo.game.plugin.PluginManager.start(org/apollo/game/plugin/PluginManager.java:153)
	at org.apollo.game.model.World.init(org/apollo/game/model/World.java:247)
	at org.apollo.Server.init(org/apollo/Server.java:158)
	at org.apollo.Server.main(org/apollo/Server.java:53)`

**Comment by garyttierney** [comment]
What release are you using?  We've been focusing on 377, so might be that your cache is slightly out of date.

Also as a note, very little maintenance has been done on the JRuby code in a long time since we started work on the `kotlin-experiments` branch at #338

**Comment by Faris-Mckay** [comment]
Sorry, turns out I had a 317 cache in my 377 folder mistakenly. 
Many thanks for the quick replies,
`INFO: Starting Apollo...
Mar 09, 2018 9:56:22 PM org.apollo.Server init
INFO: Initialized Release 377.
Mar 09, 2018 9:56:22 PM org.apollo.ServiceManager startAll
INFO: Starting services...
Mar 09, 2018 9:56:55 PM org.apollo.Server bind
INFO: Ready for connections.
Mar 09, 2018 9:56:55 PM org.apollo.Server main
INFO: Starting apollo took 33408 ms.
`
