### ISSUE TITLE
Getting -1, -2 for position difference.

### ISSUE THREAD

**Issue by Frostbit3** [apollo-rsps/apollo#91]
I was just about to start writing combat, so I changed the spawn coordinates to some place inside the wilderness. It just so happens that upon login, the wilderness interface does not come up and I am faced with a `java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer` exception. Upon further inspection, it brought me to change:
`case LONG:
			case DOUBLE:
				return new NumericalAttribute((Integer) value);`
from an `(Integer)` cast to a `(Number)` cast.

The second error, and the issue I am posting about is when being spawned to this location, and attempting to walk to a tile, the character stays in it's position and does not proceed to the designated tile. Instead outputting this:
`java.lang.IllegalArgumentException: Difference between Positions must be [-1, 1]. It was: 2 and 1
	at org.apollo.game.model.Direction.between(Direction.java:97)
	at org.apollo.game.model.entity.WalkingQueue.pulse(WalkingQueue.java:132)
	at org.apollo.game.sync.task.PrePlayerSynchronizationTask.run(PrePlayerSynchronizationTask.java:70)
	at org.apollo.game.sync.SequentialClientSynchronizer.synchronize(SequentialClientSynchronizer.java:39)
	at org.apollo.game.service.GameService.pulse(GameService.java:167)
	at org.apollo.game.GamePulseHandler.run(GamePulseHandler.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

Any thoughts would be greatly appreciated. I haven't looked much further than this.

**Comment by Major-** [comment]
I can't seem to recreate the second error - where exactly did you spawn?

**Comment by WizardJesse1** [comment]
@Major- this happen to me when i was in wilderness and tried to leave

**Comment by Major-** [comment]
For now I've disabled the walking queue verification (the cause of the second error). Thanks for reporting both of these issues - in future, please create a separate issue if there is more than one problem.

**Comment by Frostbit3** [comment]
This is still not fixed. I am in Wilderness trying to walk to tiles.

'java.lang.IllegalArgumentException: Difference between Positions must be [-1, 1]. It was: -7 and -15
	at org.apollo.game.model.Direction.between(Direction.java:97)
	at org.apollo.game.model.entity.WalkingQueue.pulse(WalkingQueue.java:132)
	at org.apollo.game.sync.task.PrePlayerSynchronizationTask.run(PrePlayerSynchronizationTask.java:70)
	at org.apollo.game.sync.SequentialClientSynchronizer.synchronize(SequentialClientSynchronizer.java:39)
	at org.apollo.game.service.GameService.pulse(GameService.java:167)
	at org.apollo.game.GamePulseHandler.run(GamePulseHandler.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)'
